//APEX Pistols
			"hgun_Pistol_01_F",
			"hgun_P07_khk_F",
//APEX Sub Machine Guns
			"SMG_05_F",
//APEX Light Machine Guns
			"LMG_03_F",
//APEX Assault Rifles
			"arifle_AK12_F",
			"arifle_AK12_GL_F",
			"arifle_AKM_F",
			"arifle_AKM_FL_F",
			"arifle_AKS_F",
			"arifle_ARX_blk_F",
			"arifle_ARX_ghex_F",
			"arifle_ARX_hex_F",
			"arifle_CTAR_blk_F",
			"arifle_CTAR_GL_blk_F",
			"arifle_CTARS_blk_F",
			"arifle_MX_GL_khk_F",
			"arifle_MX_khk_F",
			"arifle_MX_SW_khk_F",
			"arifle_MXC_khk_F",
			"arifle_MXM_khk_F",
			"arifle_SPAR_01_blk_F",
			"arifle_SPAR_01_khk_F",
			"arifle_SPAR_01_snd_F",
			"arifle_SPAR_01_GL_blk_F",
			"arifle_SPAR_01_GL_khk_F",
			"arifle_SPAR_01_GL_snd_F",
			"arifle_SPAR_02_blk_F",
			"arifle_SPAR_02_khk_F",
			"arifle_SPAR_02_snd_F",
			"arifle_SPAR_03_blk_F",
			"arifle_SPAR_03_khk_F",
			"arifle_SPAR_03_snd_F",
//APEX Sniper Rifles
			"srifle_DMR_07_blk_F",
			"srifle_DMR_07_ghex_F",
			"srifle_DMR_07_hex_F",
			"srifle_GM6_ghex_F",
			"srifle_LRR_tna_F",